id: def757be-aec7-40b4-a93b-eebc939229a3
workflowId: a1281e44-d4d2-4b2f-9a84-86faee70e7b2
workflowName: anime-downloader
status: succeeded
startedAt: '2026-01-31T19:30:26.183Z'
completedAt: '2026-01-31T19:30:54.580Z'
jobs:
  - jobName: erai-raws
    status: succeeded
    startedAt: '2026-01-31T19:30:26.184Z'
    completedAt: '2026-01-31T19:30:54.579Z'
    steps:
      - stepName: download
        status: succeeded
        startedAt: '2026-01-31T19:30:26.185Z'
        completedAt: '2026-01-31T19:30:54.579Z'
        output:
          type: model_method
          model: erai-raws
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-31T19:30:54.578Z'
            command: ./dist/mms download erai --config erai-raws-shows.yaml --auto
            durationMs: 28391
  - jobName: subsplease
    status: succeeded
    startedAt: '2026-01-31T19:30:26.184Z'
    completedAt: '2026-01-31T19:30:29.462Z'
    steps:
      - stepName: dandadan
        status: succeeded
        startedAt: '2026-01-31T19:30:26.190Z'
        completedAt: '2026-01-31T19:30:29.283Z'
        output:
          type: model_method
          model: dandadan
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-31T19:30:29.283Z'
            command: ./dist/mms download subsplease dandadan --auto
            durationMs: 3085
      - stepName: clevatess
        status: succeeded
        startedAt: '2026-01-31T19:30:26.190Z'
        completedAt: '2026-01-31T19:30:29.218Z'
        output:
          type: model_method
          model: clevatess
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-31T19:30:29.218Z'
            command: ./dist/mms download subsplease clevatess --auto
            durationMs: 3025
      - stepName: food-court-de-mata-ashita
        status: succeeded
        startedAt: '2026-01-31T19:30:26.190Z'
        completedAt: '2026-01-31T19:30:29.211Z'
        output:
          type: model_method
          model: food-court-de-mata-ashita
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-31T19:30:29.210Z'
            command: ./dist/mms download subsplease food-court-de-mata-ashita --auto
            durationMs: 3016
      - stepName: futari-solo-camp
        status: succeeded
        startedAt: '2026-01-31T19:30:26.190Z'
        completedAt: '2026-01-31T19:30:29.270Z'
        output:
          type: model_method
          model: futari-solo-camp
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-31T19:30:29.269Z'
            command: ./dist/mms download subsplease futari-solo-camp --auto
            durationMs: 3074
      - stepName: gachiakuta
        status: succeeded
        startedAt: '2026-01-31T19:30:26.190Z'
        completedAt: '2026-01-31T19:30:29.254Z'
        output:
          type: model_method
          model: gachiakuta
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-31T19:30:29.254Z'
            command: ./dist/mms download subsplease gachiakuta --auto
            durationMs: 3057
      - stepName: jidou-hanbaiki-s2
        status: succeeded
        startedAt: '2026-01-31T19:30:26.190Z'
        completedAt: '2026-01-31T19:30:29.216Z'
        output:
          type: model_method
          model: jidou-hanbaiki-s2
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-31T19:30:29.216Z'
            command: >-
              ./dist/mms download subsplease
              jidou-hanbaiki-ni-umarekawatta-ore-wa-meikyuu-wo-samayou-s2 --auto
            durationMs: 3019
      - stepName: mattaku-saikin-no-tantei
        status: succeeded
        startedAt: '2026-01-31T19:30:26.190Z'
        completedAt: '2026-01-31T19:30:29.394Z'
        output:
          type: model_method
          model: mattaku-saikin-no-tantei
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-31T19:30:29.393Z'
            command: >-
              ./dist/mms download subsplease mattaku-saikin-no-tantei-to-kitara
              --auto
            durationMs: 3199
      - stepName: mizuzokusei-no-mahoutsukai
        status: succeeded
        startedAt: '2026-01-31T19:30:26.190Z'
        completedAt: '2026-01-31T19:30:29.219Z'
        output:
          type: model_method
          model: mizuzokusei-no-mahoutsukai
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-31T19:30:29.219Z'
            command: ./dist/mms download subsplease mizuzokusei-no-mahoutsukai --auto
            durationMs: 3020
      - stepName: summer-pockets
        status: succeeded
        startedAt: '2026-01-31T19:30:26.190Z'
        completedAt: '2026-01-31T19:30:29.462Z'
        output:
          type: model_method
          model: summer-pockets
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-31T19:30:29.461Z'
            command: ./dist/mms download subsplease summer-pockets --auto
            durationMs: 3263
      - stepName: yofukashi-no-uta-s2
        status: succeeded
        startedAt: '2026-01-31T19:30:26.190Z'
        completedAt: '2026-01-31T19:30:29.213Z'
        output:
          type: model_method
          model: yofukashi-no-uta-s2
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-31T19:30:29.212Z'
            command: ./dist/mms download subsplease yofukashi-no-uta-s2 --auto
            durationMs: 3015
