id: 8e4e59e5-8dc2-4ec5-9422-456cbdb06259
workflowId: a1281e44-d4d2-4b2f-9a84-86faee70e7b2
workflowName: anime-downloader
status: succeeded
startedAt: '2026-01-31T19:21:19.549Z'
completedAt: '2026-01-31T19:21:44.853Z'
jobs:
  - jobName: erai-raws
    status: succeeded
    startedAt: '2026-01-31T19:21:19.550Z'
    completedAt: '2026-01-31T19:21:44.852Z'
    steps:
      - stepName: download
        status: succeeded
        startedAt: '2026-01-31T19:21:19.551Z'
        completedAt: '2026-01-31T19:21:44.852Z'
        output:
          type: model_method
          model: erai-raws
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-31T19:21:44.851Z'
            command: ./dist/mms download erai --config erai-raws-shows.yaml --auto
            durationMs: 25297
  - jobName: subsplease
    status: succeeded
    startedAt: '2026-01-31T19:21:19.550Z'
    completedAt: '2026-01-31T19:21:22.884Z'
    steps:
      - stepName: dandadan
        status: succeeded
        startedAt: '2026-01-31T19:21:19.556Z'
        completedAt: '2026-01-31T19:21:22.589Z'
        output:
          type: model_method
          model: dandadan
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-31T19:21:22.588Z'
            command: ./dist/mms download subsplease dandadan --auto
            durationMs: 3024
      - stepName: clevatess
        status: succeeded
        startedAt: '2026-01-31T19:21:19.556Z'
        completedAt: '2026-01-31T19:21:22.563Z'
        output:
          type: model_method
          model: clevatess
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-31T19:21:22.562Z'
            command: ./dist/mms download subsplease clevatess --auto
            durationMs: 3002
      - stepName: food-court-de-mata-ashita
        status: succeeded
        startedAt: '2026-01-31T19:21:19.556Z'
        completedAt: '2026-01-31T19:21:22.509Z'
        output:
          type: model_method
          model: food-court-de-mata-ashita
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-31T19:21:22.509Z'
            command: ./dist/mms download subsplease food-court-de-mata-ashita --auto
            durationMs: 2948
      - stepName: futari-solo-camp
        status: succeeded
        startedAt: '2026-01-31T19:21:19.557Z'
        completedAt: '2026-01-31T19:21:22.884Z'
        output:
          type: model_method
          model: futari-solo-camp
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-31T19:21:22.884Z'
            command: ./dist/mms download subsplease futari-solo-camp --auto
            durationMs: 3322
      - stepName: gachiakuta
        status: succeeded
        startedAt: '2026-01-31T19:21:19.557Z'
        completedAt: '2026-01-31T19:21:22.585Z'
        output:
          type: model_method
          model: gachiakuta
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-31T19:21:22.585Z'
            command: ./dist/mms download subsplease gachiakuta --auto
            durationMs: 3022
      - stepName: jidou-hanbaiki-s2
        status: succeeded
        startedAt: '2026-01-31T19:21:19.557Z'
        completedAt: '2026-01-31T19:21:22.543Z'
        output:
          type: model_method
          model: jidou-hanbaiki-s2
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-31T19:21:22.543Z'
            command: >-
              ./dist/mms download subsplease
              jidou-hanbaiki-ni-umarekawatta-ore-wa-meikyuu-wo-samayou-s2 --auto
            durationMs: 2980
      - stepName: mattaku-saikin-no-tantei
        status: succeeded
        startedAt: '2026-01-31T19:21:19.557Z'
        completedAt: '2026-01-31T19:21:22.509Z'
        output:
          type: model_method
          model: mattaku-saikin-no-tantei
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-31T19:21:22.507Z'
            command: >-
              ./dist/mms download subsplease mattaku-saikin-no-tantei-to-kitara
              --auto
            durationMs: 2947
      - stepName: mizuzokusei-no-mahoutsukai
        status: succeeded
        startedAt: '2026-01-31T19:21:19.557Z'
        completedAt: '2026-01-31T19:21:22.566Z'
        output:
          type: model_method
          model: mizuzokusei-no-mahoutsukai
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-31T19:21:22.566Z'
            command: ./dist/mms download subsplease mizuzokusei-no-mahoutsukai --auto
            durationMs: 3001
      - stepName: summer-pockets
        status: succeeded
        startedAt: '2026-01-31T19:21:19.557Z'
        completedAt: '2026-01-31T19:21:22.603Z'
        output:
          type: model_method
          model: summer-pockets
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-31T19:21:22.603Z'
            command: ./dist/mms download subsplease summer-pockets --auto
            durationMs: 3039
      - stepName: yofukashi-no-uta-s2
        status: succeeded
        startedAt: '2026-01-31T19:21:19.557Z'
        completedAt: '2026-01-31T19:21:22.724Z'
        output:
          type: model_method
          model: yofukashi-no-uta-s2
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-31T19:21:22.724Z'
            command: ./dist/mms download subsplease yofukashi-no-uta-s2 --auto
            durationMs: 3161
