id: f0d0c066-fb1b-4a52-86ee-208281735433
workflowId: a1281e44-d4d2-4b2f-9a84-86faee70e7b2
workflowName: anime-downloader
status: succeeded
startedAt: '2026-01-30T12:17:32.534Z'
completedAt: '2026-01-30T12:17:58.289Z'
jobs:
  - jobName: erai-raws
    status: succeeded
    startedAt: '2026-01-30T12:17:32.537Z'
    completedAt: '2026-01-30T12:17:58.288Z'
    steps:
      - stepName: download
        status: succeeded
        startedAt: '2026-01-30T12:17:32.539Z'
        completedAt: '2026-01-30T12:17:58.284Z'
        output:
          type: model_method
          model: erai-raws
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-30T12:17:58.283Z'
            command: ./dist/mms download erai --config erai-raws-shows.yaml --auto
            durationMs: 25741
  - jobName: subsplease
    status: succeeded
    startedAt: '2026-01-30T12:17:32.538Z'
    completedAt: '2026-01-30T12:17:35.856Z'
    steps:
      - stepName: dandadan
        status: succeeded
        startedAt: '2026-01-30T12:17:32.545Z'
        completedAt: '2026-01-30T12:17:35.854Z'
        output:
          type: model_method
          model: dandadan
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-30T12:17:35.853Z'
            command: ./dist/mms download subsplease dandadan --auto
            durationMs: 3299
      - stepName: clevatess
        status: succeeded
        startedAt: '2026-01-30T12:17:32.544Z'
        completedAt: '2026-01-30T12:17:35.505Z'
        output:
          type: model_method
          model: clevatess
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-30T12:17:35.504Z'
            command: ./dist/mms download subsplease clevatess --auto
            durationMs: 2954
      - stepName: food-court-de-mata-ashita
        status: succeeded
        startedAt: '2026-01-30T12:17:32.545Z'
        completedAt: '2026-01-30T12:17:35.490Z'
        output:
          type: model_method
          model: food-court-de-mata-ashita
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-30T12:17:35.489Z'
            command: ./dist/mms download subsplease food-court-de-mata-ashita --auto
            durationMs: 2938
      - stepName: futari-solo-camp
        status: succeeded
        startedAt: '2026-01-30T12:17:32.545Z'
        completedAt: '2026-01-30T12:17:35.566Z'
        output:
          type: model_method
          model: futari-solo-camp
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-30T12:17:35.566Z'
            command: ./dist/mms download subsplease futari-solo-camp --auto
            durationMs: 3014
      - stepName: gachiakuta
        status: succeeded
        startedAt: '2026-01-30T12:17:32.546Z'
        completedAt: '2026-01-30T12:17:35.554Z'
        output:
          type: model_method
          model: gachiakuta
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-30T12:17:35.545Z'
            command: ./dist/mms download subsplease gachiakuta --auto
            durationMs: 2991
      - stepName: jidou-hanbaiki-s2
        status: succeeded
        startedAt: '2026-01-30T12:17:32.546Z'
        completedAt: '2026-01-30T12:17:35.506Z'
        output:
          type: model_method
          model: jidou-hanbaiki-s2
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-30T12:17:35.505Z'
            command: >-
              ./dist/mms download subsplease
              jidou-hanbaiki-ni-umarekawatta-ore-wa-meikyuu-wo-samayou-s2 --auto
            durationMs: 2952
      - stepName: mattaku-saikin-no-tantei
        status: succeeded
        startedAt: '2026-01-30T12:17:32.546Z'
        completedAt: '2026-01-30T12:17:35.772Z'
        output:
          type: model_method
          model: mattaku-saikin-no-tantei
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-30T12:17:35.771Z'
            command: >-
              ./dist/mms download subsplease mattaku-saikin-no-tantei-to-kitara
              --auto
            durationMs: 3220
      - stepName: mizuzokusei-no-mahoutsukai
        status: succeeded
        startedAt: '2026-01-30T12:17:32.547Z'
        completedAt: '2026-01-30T12:17:35.512Z'
        output:
          type: model_method
          model: mizuzokusei-no-mahoutsukai
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-30T12:17:35.512Z'
            command: ./dist/mms download subsplease mizuzokusei-no-mahoutsukai --auto
            durationMs: 2957
      - stepName: summer-pockets
        status: succeeded
        startedAt: '2026-01-30T12:17:32.547Z'
        completedAt: '2026-01-30T12:17:35.571Z'
        output:
          type: model_method
          model: summer-pockets
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-30T12:17:35.570Z'
            command: ./dist/mms download subsplease summer-pockets --auto
            durationMs: 3016
      - stepName: yofukashi-no-uta-s2
        status: succeeded
        startedAt: '2026-01-30T12:17:32.547Z'
        completedAt: '2026-01-30T12:17:35.789Z'
        output:
          type: model_method
          model: yofukashi-no-uta-s2
          method: execute
          resourceId: ''
          resourcePath: ''
          resourceAttributes:
            exitCode: 0
            executedAt: '2026-01-30T12:17:35.789Z'
            command: ./dist/mms download subsplease yofukashi-no-uta-s2 --auto
            durationMs: 3235
