id: 4a21854c-5dcf-43ce-885a-c7b17d354f73
workflowId: a1281e44-d4d2-4b2f-9a84-86faee70e7b2
workflowName: anime-downloader
status: running
startedAt: '2026-01-29T20:33:00.217Z'
jobs:
  - jobName: erai-raws
    status: pending
    steps:
      - stepName: download
        status: pending
  - jobName: subsplease
    status: pending
    steps:
      - stepName: dandadan
        status: pending
      - stepName: clevatess
        status: pending
      - stepName: food-court-de-mata-ashita
        status: pending
      - stepName: futari-solo-camp
        status: pending
      - stepName: gachiakuta
        status: pending
      - stepName: jidou-hanbaiki-s2
        status: pending
      - stepName: mattaku-saikin-no-tantei
        status: pending
      - stepName: mizuzokusei-no-mahoutsukai
        status: pending
      - stepName: summer-pockets
        status: pending
      - stepName: yofukashi-no-uta-s2
        status: pending
