id: 8be44e38-266c-4fb7-afb1-6ae56644527d
workflowId: c6cdb905-519c-43d0-ac64-48d128bf9cb1
workflowName: run-llm
status: failed
startedAt: '2026-01-29T22:05:16.571Z'
completedAt: '2026-01-29T22:05:16.581Z'
jobs:
  - jobName: main
    status: failed
    startedAt: '2026-01-29T22:05:16.574Z'
    completedAt: '2026-01-29T22:05:16.580Z'
    steps:
      - stepName: activate-venv
        status: succeeded
        startedAt: '2026-01-29T22:05:16.574Z'
        completedAt: '2026-01-29T22:05:16.577Z'
        output:
          stdout: ''
          exitCode: 0
      - stepName: run-media-worker
        status: failed
        startedAt: '2026-01-29T22:05:16.578Z'
        completedAt: '2026-01-29T22:05:16.579Z'
        error: >
          Shell command failed: /usr/bin/bash: line 1: media-worker: command not
          found
