id: 96e9939a-365f-4562-b77a-d65067a660dc
workflowId: c6cdb905-519c-43d0-ac64-48d128bf9cb1
workflowName: run-llm
status: failed
startedAt: '2026-01-29T22:05:32.907Z'
completedAt: '2026-01-29T22:05:32.911Z'
jobs:
  - jobName: main
    status: failed
    startedAt: '2026-01-29T22:05:32.908Z'
    completedAt: '2026-01-29T22:05:32.911Z'
    steps:
      - stepName: activate-venv
        status: succeeded
        startedAt: '2026-01-29T22:05:32.908Z'
        completedAt: '2026-01-29T22:05:32.910Z'
        output:
          stdout: ''
          exitCode: 0
      - stepName: run-media-worker
        status: failed
        startedAt: '2026-01-29T22:05:32.910Z'
        completedAt: '2026-01-29T22:05:32.911Z'
        error: >
          Shell command failed: /usr/bin/bash: line 1: media-worker: command not
          found
