id: e9d6e498-f147-470f-b1af-3396c52c85a0
workflowId: c6cdb905-519c-43d0-ac64-48d128bf9cb1
workflowName: run-llm
status: failed
startedAt: '2026-01-29T22:47:43.523Z'
completedAt: '2026-01-29T22:47:50.305Z'
jobs:
  - jobName: main
    status: failed
    startedAt: '2026-01-29T22:47:43.524Z'
    completedAt: '2026-01-29T22:47:50.304Z'
    steps:
      - stepName: run-media-worker
        status: failed
        startedAt: '2026-01-29T22:47:43.524Z'
        completedAt: '2026-01-29T22:47:50.304Z'
        error: >
          Shell command failed: 2026-01-29 14:47:43,774 - INFO - Starting media
          job worker

          2026-01-29 14:47:48,782 - ERROR - Failed to connect to MongoDB:
          localhost:27017: [Errno 111] Connection refused (configured timeouts:
          socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout:
          5.0s, Topology Description: <TopologyDescription id:
          697be38f6b6f9f1ff8664dd8, topology_type: Unknown, servers:
          [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt:
          None, error=AutoReconnect('localhost:27017: [Errno 111] Connection
          refused (configured timeouts: socketTimeoutMS: 20000.0ms,
          connectTimeoutMS: 20000.0ms)')>]>

          2026-01-29 14:47:48,782 - CRITICAL - Database connection failed: Could
          not connect to MongoDB: localhost:27017: [Errno 111] Connection
          refused (configured timeouts: socketTimeoutMS: 20000.0ms,
          connectTimeoutMS: 20000.0ms), Timeout: 5.0s, Topology Description:
          <TopologyDescription id: 697be38f6b6f9f1ff8664dd8, topology_type:
          Unknown, servers: [<ServerDescription ('localhost', 27017)
          server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017:
          [Errno 111] Connection refused (configured timeouts: socketTimeoutMS:
          20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
