id: 6dc653b5-c98d-48a3-b8cd-ad46ab089ceb
workflowId: c6cdb905-519c-43d0-ac64-48d128bf9cb1
workflowName: run-llm
status: succeeded
startedAt: '2026-01-30T12:11:35.199Z'
completedAt: '2026-01-30T12:11:46.480Z'
jobs:
  - jobName: main
    status: succeeded
    startedAt: '2026-01-30T12:11:35.202Z'
    completedAt: '2026-01-30T12:11:46.479Z'
    steps:
      - stepName: run-media-worker
        status: succeeded
        startedAt: '2026-01-30T12:11:35.202Z'
        completedAt: '2026-01-30T12:11:46.474Z'
        output:
          stdout: ''
          exitCode: 0
